version: '3.5'
services:
  catchapp-db:
    image: postgres
    container_name: catchapp-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -U postgres
      interval: 5m
      timeout: 10s
      retries: 5

  catchapp-backend:
    build: .
    container_name: catchapp-backend
    restart: unless-stopped
    ports:
      - "5050:5050"
    env_file:
      - .env
    depends_on:
      - catchapp-db
    volumes:
      - ./static:/app/static
      - ./media:/app/media

  rabbitmq-dev:
    image: rabbitmq:latest
    container_name: rabbitmq-dev
    restart: unless-stopped
    healthcheck:
      test: nc -z localhost 5672
      interval: 10m
      timeout: 10s
      retries: 5
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  celery-dev:
    build: .
    container_name: celery-dev
    restart: unless-stopped
    command: celery
    env_file:
      - .env
    depends_on:
      - catchapp-backend
      - rabbitmq-dev

  celery-beat-dev:
    build: .
    container_name: celery-beat-dev
    restart: unless-stopped
    command: celery-beat
    env_file:
      - .env
    depends_on:
      - catchapp-backend
      - rabbitmq-dev


volumes:
  postgres_data:
